concourse-aws-user/main.tf
This is missed while migrated to concourse module
=> Add permissions to concourse users

main.tf, variables.tf
Revert the auth0 multiple tenant changes, as now we are maintaining only justice-cloud-platform auth0 tenant
=> Revert the auth0 multiple tenant changes.

concourse-aws-user/main.tf
This is for the EKS cluster pipeline.
=> Update concourse user permissions

concourse-aws-user/main.tf
Add AttachUserPolicy permission for concourse user to create EKS cluster and apply components including concourse
=> Add AttachUserPolicy permission for concourse user

concourse-aws-user/main.tf
This is for creating/updatin/deleting ses resources.
This to apply through pipeline
https://github.com/ministryofjustice/cloud-platform-environments/pull/3395/files
=> Add ses permission for concourse user

main.tf, variables.tf
- Added dockerhub credentials in order to avoid reaching dockerhub API limits when pulling
- Added CloudPlatform Github Access Token in order to check for PR within cloud-platform-infrastructure
=> tokens and dockerhub credentials

policy.tf
This commit connects to
https://github.com/ministryofjustice/cloud-platform-environments/pull/3788/files
and relates to the addition of kinesis and apigateway creation and
management.
=> Add kinesis and apigateway permission to concourse user

policy.tf
This fixes divergence pipeline for EKS
=> Added new permission to list policies.

main.tf, templates/values.yaml, variables.tf
Added Dockerhub credentials and ImagePullSecrets to concourse Helm Chart
=> Added dockerhub credentials to concourse in order to pull images in authenticated way

example/versions.tf, versions.tf
This PR contains all changes in this repository made by the command `terraform 0.13upgrade` tool.
=> Terraform 0.13 upgrade for repository

main.tf
This is created in cloud-platform-concourse repo. https://github.com/ministryofjustice/cloud-platform-concourse/tree/main/pipelines/manager/main/build-environments
=> Remove serrviceaccount for manager cluster.

policy.tf
fixes https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/create-test-destroy/jobs/destroy-cluster/builds/53
=> disable dnssec needed before zone delete

main.tf, versions.tf
Also moved locals to the top of the file (convention)
=> Replaced null_resources with kubectl_manifest

pipelines/manager/main/divergence.yaml
For EKS cluster and for components.
=> Divergence pipeline for live cluster

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/reporting.yaml, pipelines/manager/main/scanning.yaml
Revisited all the jobs and updated the schedule accordingly, this is to reduce no of runs.
=> Update schedule for jobs

pipelines/manager/main/scanning.yaml
Update schedule for sonar-scanner
=> Update schedule for sonar-scanner

pipelines/manager/main/eks-create-test-destroy.yaml
This is to test cluster creation and destroy works fine with tools image
=> Ugrade tools image to latest

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/build-test-cluster.yaml
This is for EKS currently as Kops still need old Image
=> Upgrade tools image to use the latest v2.0

pipelines/manager/main/cloud-platform-infrastructure.yaml, pipelines/manager/main/divergence.yaml
This version got the updates related to 1.20 K8s
=> Update cli image to use the latest version

templates/values.yaml
This is temp as we are looking into running a job to clear volume and recycle pods.
=> This is to fix concourse OOM issue

pipelines/manager/main/reporting.yaml
This is by running multiple tasks(go and rspec) tests  in parallel.
=> Create single job for live integration tests

pipelines/manager/main/divergence.yaml
This is for divergence pipeline.
=> Update cli image to use the right version

pipelines/manager/main/environments-live.yaml
This will send a low-priority slack message, with the deleted namespaces in "live"
=> Pipeline to run detect deleted namespaces in "live"

pipelines/manager/main/maintenance.yaml
This will recycle the oldest node in the default node group for live
=> feat(node-recycle): :sparkles: Add Live cluster node recycler

pipelines/manager/main/cloud-platform-infrastructure.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.14.8
=> Bump cli image version

pipelines/manager/main/divergence.yaml, pipelines/manager/main/maintenance.yaml
Related to: https://github.com/ministryofjustice/cloud-platform/issues/3677
=> Remove live-1 cluster related pipeline and concourse jobs

pipelines/manager/main/eks-create-test-destroy.yaml
This is to use the  go-integration-test-image
=> Update run-integration-tests in create-test-destroy

pipelines/manager/main/build-test-cluster.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/maintenance.yaml
This is to use the latest tools image and updated create cluster script
=> Update tools image and create cluster run

pipelines/manager/main/reporting.yaml
- test(manager): add go tests to testing pipeline
- fix(reporting): fix manager pipeline wording
=> Fix incorrect naming of pipeline

pipelines/manager/main/infrastructure-vpc.yaml
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4008
=> Add pipeline for cloud-platform-aws/vpc folder

pipelines/manager/main/build-test-cluster.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/reporting.yaml
- feat(tools): bump image version to 2.2.4
- fix(yaml): incorrect anchoring format
=> Bump tools image to 2.2.4 and fix formatting

pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc.yaml
Setting `pipefail` still returns `2` on any terraform changes and the pipeline fails. We dont want to pipeline to fail on exit-code 2. Hence, remove the pipefail and check status.
=> Check PIPESTATUS for 1 and exit 1 else 0

pipelines/manager/main/environments-live-2.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml
This is for apply, apply-namespace, plan pipeline
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4109
=> Create new-pipeline for live-2

pipelines/manager/main/reporting.yaml
This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/4106
=> Create integration test pipeline for live-2

pipelines/manager/main/divergence.yaml
remove unused env vars, replace s3 kubeconfig download with aws eks command
=> refactor: live-components and manager-components jobs

pipelines/manager/main/environments-live-2.yaml
This is to check the cause of the github API rate limit exceeded issue
We will keep this disabled for couple of days to test API limit
=> Disable live-2 apply namespaces pipeline

pipelines/manager/main/environments-live-2.yaml
=> Update group in live-2 apply pipeline

pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc.yaml
This is to remove pull-request resource for apply pipelines, instead use git resource, this is to control rate limit
=> Use git resource for apply pipelines

pipelines/manager/main/infrastructure-live-2.yaml
This is to fix the error:
invalid payload (missing repository)
=> Remove put for live-2 pipeline

pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/environments-live-2.yaml
This PR updates the environment-live-2 pipeline to include apply-namespace changes with the latest cli command. This also removes the pull-request resource used when merging and use git
=> Update live-2 environment pipeline

pipelines/manager/main/environments-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml
- Update path in live-2 environments pipeline, this is to fix the pipeline trigger when there are any changes in the path
- Update live infrastructure PR to use git resource, This is to match with the manager and live-2 pipeline
=> Update pipelines related to PR resource

main.tf, resources/alerts/cloud-platform-reports-cronjobs.yaml
This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/3768
=> Create alerts for hoodaw cronjobs

pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml
This is to rename and create new pipelines
=> Update infrastructure pipelines

pipelines/manager/main/environments-live-2.yaml
This is to provide build info as comments in the PR
=> Add comments in git PR

pipelines/manager/main/environments-live-2.yaml, pipelines/manager/main/environments-live.yaml
This is to provide concourse build info as commit on the PR
=> Add comment on the Merged PR

pipelines/manager/main/maintenance.yaml
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4073
=> Create pipeline delete old snap

main.tf, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, policy.tf
This is for manager-concourse-cloud-platform-admin
=> Remove the key not used

pipelines/manager/main/infrastructure-live.yaml
=> Enable infrastructure apply pipeline

pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml
infrastructure vpc pipeline tools image version updated for terraform 1.2.5
=> update tools image for terraform upgrade

pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml
This is to do a git pull, so it always runs the latest from the main branch 
related to:
https://github.com/ministryofjustice/cloud-platform/issues/4382
=> Update infrastructure apply pipeline

README.md, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/reporting.yaml
This is for both tools and cli
=> Upgrade concourse to use terrafrom 1.2.5

pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml
This is for git resource to trigger on every run
=> Remove path for infra pipelines

pipelines/manager/main/infrastructure-live-2.yaml
This PR restores infrastructure-live-2 pipeline utilising cloud-platform-cli redact functionality
=> add infrastructure live-2 pipeline plan/apply with cli tf commands

pipelines/manager/main/infrastructure-live.yaml
This PR restores infrastructure-live pipeline utilising cloud-platform-cli redact functionality
=> add infrastructure live pipeline plan/apply with cli terraform commands

resources/alerts/cloud-platform-reports-cronjobs.yaml
This is to fix the PrometheusOperatorReconcileErrors
=> Update prometheus alert for cronjob

main.tf, policy.tf
=> Move iam:ListOpenIDConnectProviders to not be resource-bound

pipelines/manager/main/environments-live.yaml
Fixing ` unknown resource 'every-240m'`
=> Fix resource every-240m

README.md, policy.tf
To fix error: ```Error: error updating IAM policy arn:aws:iam::754256621582:policy/cloud-platform/manager-concourse-user-policy: LimitExceeded: Cannot exceed quota for PolicySize: 6144```
=> Split concourse user policy to fix max policy limit

pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/reporting.yaml
https://github.com/ministryofjustice/cloud-platform-cli/pull/409
https://github.com/ministryofjustice/cloud-platform-environments-checker/pull/52
=> Bump cli image on all pipelines

pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
relates to https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4588
=> update cli release for all pipelines

policy.tf
For ministryofjustice/cloud-platform#4224.
=> Add CloudFront permissions to Concourse

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml
- Bump cloud-platform cli to 1.29.0
- Update tools image to 2.5.0
=> bump cloud-platform cli and tools image

pipelines/manager/main/reporting.yaml
https://github.com/ministryofjustice/cloud-platform-tools-image/releases/tag/2.6.0
=> Bump infra image that run tests

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-tools-image/releases/tag/2.6.0
=> Bump tools image and infra image on all pipelines

pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml
This is to fix `version is missing from previous step`
=> Add missing resource_type and fetch latest version

pipelines/manager/main/cordon-and-drain-nodes.yaml
=> perf: ⚡️ increase to 5 mins between each node to alleviate ip

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5247
=> Bump cli image to 1.30.13

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
Reverts ministryofjustice/cloud-platform-terraform-concourse#339
Pipeline fails after the bump. Reverting
=> Revert "Bump cli image to 1.30.13"

pipelines/manager/main/reporting.yaml
as per guidance https://onsi.github.io/ginkgo/#recommended-continuous-integration-configuration
=> update ginkgo CLI params for deprecated commands

pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.32.6
=> chore: 🤖 bump cli image

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/reporting.yaml
relates to ministryofjustice/cloud-platform#5355
=> bump cli and tools image

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/migrate-module.yaml, pipelines/manager/main/reporting.yaml, pipelines/manager/main/vulnerability-report.yaml
- [feat: 🎸 add vulnerabilty report pipeline](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/commit/bb8bcaddb6f56844023bf30c0e9be57beed62dbb)
- [chore: 🤖 update tools image version](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/commit/471154a6fe87128d10a8f0fedf7082bd6cb2905a)
=> Vuln report pipeline

policy.tf
relates to ministryofjustice/cloud-platform#5610
=> feat: 🎸 add route53 resolver config creation permissions

templates/values.yaml
relates to ministryofjustice/cloud-platform#5837
=> feat: 🎸 enable hardAntiAffinity for worker pod node separation

pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml
relates to ministryofjustice/cloud-platform#5760
=> ci: 🎡 set infra plan and apply pipelines to run sequentially

README.md, hoodaw_irsa.tf
- **feat(TF): Add count to all hoodaw irsa resources to stop failing on concourse test cluster builds**
- **feat(TF): add count to data block**
- **feat(TF): add indexing to the hoodaw irsa to stop failing on data inputs**
=> hoodaw irsa role fix to stop failure when adding to a test cluster

pipelines/manager/main/support-issues.yaml
Adjust the days for which the hammer support tickets are created
=> chore: 🤖 change support issue days

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
✅ Closes: https://github.com/ministryofjustice/cloud-platform/issues/6026
- remove node once it has been drained, by updating the desired and max node count in the node group config
- updated cli image tags to latest image
=> perf: ⚡️ remove drained nodes from node group

pipelines/manager/main/maintenance.yaml
to protect against ip starvation issues
=> chore: 🤖 temp turn off nightly node recycle

pipelines/manager/main/maintenance.yaml
- Fixes bootstrap errors due to unused resources.
-
-
=> fix: comment out unused resources to fix bootstrap

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/compare/1.33.4...1.34.1
include feat to recognise rds version mismatch, raise a pr and post to ask
=> chore: 🤖 bump concouse cli image

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.34.4
=> chore: 🤖 update cli to fix sed bug

pipelines/manager/main/maintenance.yaml
- this was turned off during the IP starvation issues, we can now turn this back on
=> feat: 🎸 turn back on nightly node recycle

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
- skip pr creation for rds version drift if a pr is already open
https://github.com/ministryofjustice/cloud-platform-cli/compare/1.34.8...1.34.10
=> chore: 🤖 bump cli to skip pr creation if already exists

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.35.0
=> chore: 🤖 bump cli to output tf summary

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
- correct flag casing
- bump cli
=> refactor: 💡 prNumber -> pr-number (consistent casing)

pipelines/manager/main/infrastructure-live.yaml
=> fix: 🐛 plan path for live

README.md, example/concourse.tf, example/variables.tf, main.tf, variables.tf
relates to ministryofjustice/cloud-platform#5986
=> chore: 🤖 remove redundant sonarqube vars and refs

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/migrate-module.yaml, pipelines/manager/main/support-issues.yaml, pipelines/manager/main/vulnerability-report.yaml
- Add go delete job to Concourse
- Bump tools image version
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/5487
=> feat: Add go delete job to Concourse

pipelines/manager/main/maintenance.yaml
- Update kubeconfig path
- Remove unused inputs
=> fix: Update kubeconfig path

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, templates/values.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.37.1
=> perf: ⚡️ run apply pipelines in parallel

templates/values.yaml
https://moj-digital-tools.pagerduty.com/incidents/Q0L3AVM21LEITK?utm_campaign=channel&utm_source=slack
=> perf: ⚡️ lower cpu limits for workers

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, templates/values.yaml
https://github.com/ministryofjustice/cloud-platform-cli/tree/refs/tags/1.37.2
=> chore: 🤖 bump cli to lower concurrent tf apply

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/tree/refs/tags/1.37.3
=> chore: 🤖 bump cli

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.37.5
=> chore: 🤖 bump cli to turn off concurrency

pipelines/manager/main/support-issues.yaml
Following our discussion to create a ticket to monitor secondary support tickets
=> feat: 🎸 🔧 Secondary Support tickets

templates/values.yaml
- increase n concourse workers
=> chore: 🤖 increase number of workers

README.md, main.tf, templates/values.yaml, variables.tf
- fix typo
- bump requests and limits
=> perf: ⚡️ bump limits and requests for workers

templates/values.yaml
- increase web resources
- increase replicas
=> perf: ⚡️ increase workers and web limits

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/compare/1.37.6...1.37.12
=> chore: 🤖 cli concurrency

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/migrate-module.yaml, pipelines/manager/main/support-issues.yaml, pipelines/manager/main/vulnerability-report.yaml
https://github.com/ministryofjustice/cloud-platform-tools-image/releases/tag/2.9.9
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.37.13
=> chore: 🤖 bump tools and cli

pipelines/manager/main/environments-live.yaml
relates to ministryofjustice/cloud-platform#6278
=> chore: 🤖 skipfile is honoured in single namespace apply

pipelines/manager/main/environments-live.yaml
This reverts commit 99144e0b155aecc76b16201d42dc610a4e29cbc5.
=> Revert "chore: 🤖 skipfile is honoured in single namespace apply"

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
- Implement auto approve mechanism for cloud-platform-environments PR in `plan-live` pipeline
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/5996
=> feat: Implement auto approve in plan-live pipeline

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
- remove unused variables
- bump cloud-platform-cli version
=> fix: remove unused variables and bump cli version

pipelines/manager/main/environments-live.yaml
- prevent failing silently
- throw error if command errors
=> fix: 🐛 fail on error

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
- bump cli version
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.39.3
=> chore: bump cli version

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
[release](https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.39.4)
=> chore: 🤖 bump cli image for latest release

README.md, main.tf, variables.tf
relates to ministryofjustice/cloud-platform#6461
=> feat: 🎸 add var and k8s secret for environments-live s3 bucket

pipelines/manager/main/environments-live.yaml
relates to ministryofjustice/cloud-platform#6461
=> refactor: 💡 tidy s3 paths, use env-live bucket name ENVVAR

pipelines/manager/main/reporting.yaml
[release](https://github.com/ministryofjustice/cloud-platform-environments-checker/releases/tag/3.4.0)
=> chore: 🤖 bump env checker reporting image

pipelines/manager/main/support-issues.yaml
- update actions for secondary support
=> docs: ✏️ actions for secondasry support

README.md, main.tf, pipelines/manager/main/reporting.yaml, variables.tf
This pr is adding kubernetes secret for the github team filter api key
=> Add GitHub filter api key

.github/workflows/documentation.yml, .github/workflows/push-terraform-module-version.yaml, .github/workflows/unit.yaml
=> Pin actions

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.40.3
=> chore: 🤖 bump cli (unfurl tf summary by default)

pipelines/manager/main/s3-bucket-deleter.yaml
tested on a dummy bucket [here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/delete-s3-bucket-contents/jobs/delete-s3-bucket-contents/builds/2)
in `pipelines/manager/main/`
```
fly -t manager set-pipeline -p delete-s3-bucket-contents -c s3-bucket-deleter.yaml --var "bucket_name=[YOUR_BUCKET_NAME]"
```
=> feat: 🎸 add a temp pipeline for huge s3 bucket cleanup

pipelines/manager/main/apply-live-cluster-user-roles.yaml, pipelines/manager/main/env-apply-live-cluster-user-roles.yaml, pipelines/manager/main/environments-live.yaml
- Moves the apply-live-cluster-user-roles into it's own pipeline
=> ci: move apply-live-cluster-roles to new pipeline

pipelines/manager/main/environments-live.yaml
=> fix: update cloud-platform-cli command

pipelines/manager/main/environments-live.yaml
- add github token for `process-rds-error-namespaces`
=> fix: add tf var github token

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/s3-bucket-deleter.yaml
=> chore: bump cli image

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/s3-bucket-deleter.yaml
=> ci: bump cli image to tag: "1.43.0"

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/s3-bucket-deleter.yaml
Bumping to 1.43.1 that includes a fix for the cluster create pipeline.
=> Bumping to latest image to fix cluster create

pipelines/manager/main/bootstrap.yaml, pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-account.yaml, pipelines/manager/main/infrastructure-global-resources.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/infrastructure-vpc-live-1.yaml, pipelines/manager/main/infrastructure-vpc-live-2.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/migrate-module.yaml, pipelines/manager/main/s3-bucket-deleter.yaml, pipelines/manager/main/support-issues.yaml, pipelines/manager/main/vulnerability-report.yaml
Update tool images to 2.10.1 and cli images to 1.44.1 - Updating Kubectl to version 1.30.4 
Related issue: [#6722](https://github.com/ministryofjustice/cloud-platform/issues/6722)
=> Update tool images to 2.10.1 and cli images to 1.44.1

pipelines/manager/main/environments-live.yaml
- adds new field (`ns_contains_skip_file`) which will be useful for auto approval
eg. 
```
{
...
"resource": "module.secrets_manager.data.aws_iam_policy_document.irsa_policy",
"attribute": [
"json"
]
},
{
"resource": "module.secrets_manager.aws_secretsmanager_secret.secret",
"attribute": []
},
{
"resource": "module.secrets_manager.module.irsa.data.aws_partition.current",
"attribute": [
"partition"
]
}
],
"ns_contains_skip_file": true
}
```
=> chore: 🤖 add ns_contains_skip_file bool to plan.json

pipelines/manager/main/opensearch.yaml
- update pipeline for opensearch new alert
relates to https://github.com/ministryofjustice/cloud-platform/issues/6909
=> ci: update pipeline for opensearch new alert

README.md, hoodaw_irsa.tf, main.tf, versions.tf
relates to ministryofjustice/cloud-platform#7386
=> chore: 🤖 bump helm provider and syntax

main.tf
- Bumps chart to 17.4.0 and app to 7.12.0
=> chore: bump concourse chart to 17.4.0

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/tag-velero-s3.yaml
[release](https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.47.1)
relates to ministryofjustice/cloud-platform#7442
=> chore: 🤖 bump cli image for all pipelines

pipelines/manager/main/maintenance.yaml
- add modsec fb restart job
- it would be a interim solution before we proceed https://github.com/ministryofjustice/cloud-platform/issues/7515
=> ci: add modsec fb restart job

secrets.tf
=> chore: 🤖 fixing underscores to dashes for secret names

pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml, pipelines/manager/main/tag-velero-s3.yaml
relates to ministryofjustice/cloud-platform#7549
=> chore: 🤖 bump cli images for all remaining pipes

pipelines/manager/main/kraken.yaml
relates to ministryofjustice/cloud-platform#7613
(no-ops)
=> chore: 🤖 switch kraken pipeline to use new dedicated gh token

pipelines/disabled/kraken.yaml, pipelines/disabled/tag-velero-s3.yaml, pipelines/manager/main/cordon-and-drain-nodes.yaml, pipelines/manager/main/create-cluster.yaml, pipelines/manager/main/custom-cluster.yaml, pipelines/manager/main/delete-cluster.yaml, pipelines/manager/main/divergence-live-2.yaml, pipelines/manager/main/divergence.yaml, pipelines/manager/main/eks-create-test-destroy.yaml, pipelines/manager/main/environments-live.yaml, pipelines/manager/main/hoodaw.yaml, pipelines/manager/main/infrastructure-live-2.yaml, pipelines/manager/main/infrastructure-live.yaml, pipelines/manager/main/infrastructure-manager.yaml, pipelines/manager/main/maintenance.yaml
Updates CLI image to latest
Relates to: https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=95110859&issue=ministryofjustice%7Ccloud-platform-security-issues%7C19
=> Update CLI images for all pipelines
