concourse-aws-user/main.tf
main.tf
variables.tf

Add CreateOpenIDConnectProvider role, for concourse manager user to create eks cluster.
Add dependency for prometheus to install concourse

Concourse eks pipeline

---

main.tf
variables.tf

This will be used by concourse jobs that post data to
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk

Add HOODAW API key secret

---

main.tf

Tell terraform that the kubernetes secret must be recreated whenever the
IAM user/policy is changed.

Add a dependency on the IAM user to hoodaw-creds

---

main.tf
templates/values.yaml
variables.tf

Use helm chart version 13.0.0
Remove imageTag and allow helm to use the default value. Thatway we dont need to maintain seperate image and just maintain helm versions. https://github.com/concourse/concourse-chart/blob/master/values.yaml#L24
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1946

Upgrade concourse helm chart to use latest version 13.0.0

---

main.tf

It should be called "value" instead of "key", so we are consistent with the other values.

Renaming field.

---

policy.tf

When you make changes to an IAM customer managed policy, and when AWS
makes changes to an AWS managed policy, the changed policy doesn't
overwrite the existing policy. Instead, IAM creates a new version of the
managed policy. IAM stores up to five versions of your customer managed
policies. IAM does not support versioning for inline policies.
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-versioning.html?icmpid=docs_iam_console

Add CreatePolicyVersion to concourse permissions

---

main.tf
policy.tf

This is required in order to execute global-resources folder, cloud-platform account and network.

Added admin user for cloud-platform plan/apply pipellines

---

main.tf
variables.tf

This will contain the value of `hoodaw_host`.
After merging, create a 1.5.2 release of this module.
Once this exists, pipelines will no longer need to
hard-code the URL of the web application. Instead,
they will get both the API key and the hostname
from the same secret.
This will make it easier if we move the
application to a different URL, because we will
only need to change the value in one place.
Besides, hard-coded strings are icky.
blocks https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1025

Add a 'hostname' key to the HOODAW secret

---

policy.tf

The AWS Athena  uses aws_glue service to create a data catalog

Allow concourse user to have full access to AWS Glue

---

example/main.tf

By removing the version of the Terraform provider, tf init will automatically pull the latest version. As this is an example, it would be wise not to pin and let the user decide on the version

Remove version from Helm Terraform provider

---

main.tf
variables.tf

This change puts the value of 
`github_actions_secrets_token` into a kubernetes
secret in the concourse-main namespace, to make
it available to the environments terraform 
concourse pipelines.
depends on https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1073

Create github_actions_secrets_token k8s secret

---

main.tf

Can only have alphanumeric, - or . characters

Fix the k8s secret name to github-actions-secrets-token

---

policy.tf

The v15.6.0 terraform-aws-eks module add tagging the resources and hence concourse need permissions to set those tags when creating the cluster

Add TagPolicy and TagOpenIDConnectProvider permissions

---

bin/force-pipeline-state
pipelines/manager/main/bootstrap.yaml
pipelines/manager/main/build-test-cluster.yaml
pipelines/manager/main/cloud-platform-infrastructure.yaml
pipelines/manager/main/create-test-destroy.yaml
pipelines/manager/main/divergence.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/environments-terraform.yaml
pipelines/manager/main/hoodaw.yaml
pipelines/manager/main/maintenance.yaml
pipelines/manager/main/reporting.yaml
pipelines/manager/main/scanning.yaml

As discussed in https://github.com/ministryofjustice/cloud-platform/issues/3017 we are pipelines within the terraform module repo.
Still pending to integrate the terraform files to build the kubeconfigs

Moving pipelines to cloud-platform-terraform-concourse repo

---

main.tf
variables.tf
versions.tf

Divergence is failing as we didn't allow minor upgrades to rds, updated the module to allow minor upgrades to rds

Update module to allow minor upgrades to rds

---

pipelines/manager/main/kops-create-test-destroy.yaml

This is to update create-test-destroy for kops, to have a separate job for running integration tests.
- This separate integration tests job will enable to review of the failed test and re-run it if needed.
- Destroy cluster job have a dependency on integration test job, so it will only run if the tests are passed.

Create-test-destroy pipeline for kops

---

pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/kops-create-test-destroy.yaml

This is to avoid leftover clusters over the weekend when tests fail. Also, we won't be pushing changes to the infra repo during the weekend, so this is not needed over the weekend.

Update create-test-destroy to run on weekdays

---

templates/values.yaml

This is to fix "ProcessNotFoundError",
suggestion below to tune resource values:
https://github.com/concourse/concourse/wiki/Error-Messages-And-What-To-Do-About-Them#processnotfounderror

Increase resource limit to 8gi

---

pipelines/manager/main/maintenance.yaml
pipelines/manager/main/reporting.yaml

Connected to https://github.com/ministryofjustice/cloud-platform/issues/3294
To get a better idea of which pipelines run against which clusters, I felt we could first uniform the pipeline naming in reports and maintenance. This should give us a better idea of what's missing in "live".

Rename ambigious pipeline names

---

pipelines/manager/main/eks-create-test-destroy.yaml

After upgrading to the new k8's provider, we don't have the option to set load_config to false,
so need to remove the config path to use the K8s provider

Remove KUBE_CONFIG_PATH env var

---

templates/values.yaml

Reverts ministryofjustice/cloud-platform-terraform-concourse#79
The volume filling up issue is fixed and hence the increased memory and worker pv size can be reverted and have longer build logs.

Revert "This is to fix concourse OOM issue"

---

pipelines/manager/main/maintenance.yaml

This job looking at live-1 but not live caused wrongly deleting records. We don’t need this job anymore,external-dns sync does delete DNS when ingress is removed and it maintains the right sync.

Remove aws-delete-excess-dns job

---

pipelines/manager/main/eks-create-test-destroy.yaml

Now the OPA valid-host policy is updated to accept, integration test zone, used for the external-dns test.
This will fix the below error, when deleting the cluster
```
Command: cd terraform/aws-accounts/cloud-platform-aws/vpc/eks/components; terraform destroy  -auto-approve failed.
Error: configmaps "valid-host" not found
```

UPdated test script,keep OPA configmap valid-host

---

pipelines/manager/main/reporting.yaml

This job runs the script to compare the namespaces, which exist in the cluster to those which are defined in the env-repo.
https://github.com/ministryofjustice/cloud-platform-environments-checker/blob/main/bin/orphaned_namespaces.rb

Create new job for live-orphaned-namespaces

---

pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/reporting.yaml

This version got the fix for ingress tests, with sleep time.

Update golang tests to use the latest image tag

---

pipelines/manager/main/environments-live.yaml

This is to limit the step's execution.
This run waiting for the below input and stuck for a couple of days without any error, this timeout should fix that issue in future runs
Username for 'https://github.com':
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live/builds/1242

Add timeout for apply and plan pipeline

---

pipelines/manager/main/environments-live.yaml

This pipeline will delete the namespace, deleted in the PR
We disabled it during live-1 to live migration, enabling it back as migration is now completed

Enable auto namespace deletion for live

---

pipelines/manager/main/cloud-platform-infrastructure.yaml
pipelines/manager/main/divergence.yaml

https://github.com/ministryofjustice/cloud-platform-cli/pull/174
This has the aws cli version 2.7.6.

Bump cli image to 1.14.10

---

pipelines/manager/main/environments-live.yaml

Overview
---
Due to the way the cloud-platform-environments repository is setup, if you raise a PR that doesn't meet the paths glob it cannot be merged. This change removes the need for a paths globs, which means the terraform plan pipeline will run regardless of the files changed.

Remove the paths option from live environments pipeline

---

pipelines/manager/main/reporting.yaml

this was previously ommited due to the difficulty of switch cluster types. Due to a refactor, this is now alot easier and go tests in manager are now possible.

Add go tests to the manager integration test pipeline

---

pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

This change should report to github in two separate jobs rather than one. By changing where to failure occurs I'm hoping that in the event of one of the tasks failing, concourse will then send a failure to GitHub. The context_base and context naming is to allow both live and manager clusters to report their status individually.

Change how infrastructure reports status to GitHub

---

pipelines/manager/main/maintenance.yaml

This PR re-instates the previous recycle schedule. We changed it when the tool was re-written, but now feel like it can be trusted.

Trigger recycle node job three times per morning

---

pipelines/manager/main/maintenance.yaml

Once every morning from Monday-Friday we should recycle a 'manager' cluster node. This form of chaos engineering ensures we can survive with ephemeral nodes and reminds us to treat nodes as cattle.

Add manager node recycle task

---

pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/reporting.yaml

Overtime we have replaced the Rspec tests with Go. Once this PR is merged, the `smoke-tests` directory will be removed from `infrastructure`.

Remove ruby tests from all pipelines

---

pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

execute-components-plan returns success by default. Add on_success step hook to return success.
This also fix the pipeline which is always green irrespective of failure or success

Add on_success for execute-components-plan task

---

pipelines/manager/main/maintenance.yaml

This is proving to be troublesome. As the recycler purges 1/5 nodes per day, it has a 1/5 chance of dying during runtime. After a discussion it was decided this may be best to keep it manual.

Remove trigger from manager recycler

---

pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/reporting.yaml

This PR changes the flaky test retry from 3 to 2 so we get a succinct failure, rather than the panic displayed here: https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/5290.
It also fixes an anchoring error a yaml linter complains about.

Fix test timeout and yaml anchor errors

---

pipelines/manager/main/reporting.yaml

This was missed in a previous PR and will fix the error outlined here:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/manager-integration-tests/builds/159

Change flaky tests from 3 to 2

---

pipelines/manager/main/maintenance.yaml

This is hurting my requirement for green (working) pipelines. Concourse runs on manager and running the recycle job gives us a 1/4 chance of deleting itself - we should remove this pipeline as it will never be manually triggered and just sit in a failed state.

Remove manager recycle job

---

pipelines/manager/main/reporting.yaml

There's no need for us to host config in an s3 bucket if we can generate using the aws cli.

Use AWS cli to auth in reporting

---

pipelines/manager/main/infrastructure-account.yaml
pipelines/manager/main/infrastructure-global-resources.yaml

Related to: https://github.com/ministryofjustice/cloud-platform/issues/4008
This pipeline triggers on PR to account/ folder changes comparing terraform state with the `cloud-platform-aws` account and apply the terraform changes.
To run this pipeline manually, you will need aws credentials for `cloud-platform-aws` and `auth0` credentials for the Auth0 account which defaults to  `justice-cloud-platform.eu.auth0.com`

Add pipeline to do plan/apply account level, global-resources terraform changes

---

policy.tf

The policy didnot get updated because of the policy character restrictions. 
```
Error: error updating IAM policy arn:aws:iam::754256621582:policy/cloud-platform/manager-concourse-user-policy: LimitExceeded: Cannot exceed quota for PolicySize: 6144
status code: 409, request id: ddc5f7ba-4039-4a76-ac8f-37b9e5fa6b38
on .terraform/modules/concourse/policy.tf line 614, in resource "aws_iam_policy" "policy":
614: resource "aws_iam_policy" "policy" {```
This PR fixes the error by spliting the policy into 2 and attaching both to the iam user.

Split policy as there are chars restrictions of 6144

---

pipelines/manager/main/environments-live.yaml

This is to clear confusion vpc_name vs cluster_name
Once all modules using cluster_name are updated, this can be removed "TF_VAR_cluster_name"

Update env var related to vpc_name

---

pipelines/manager/main/divergence-live-2.yaml
pipelines/manager/main/divergence.yaml

This PR is for creating a new divergence pipeline to provide coverage for `live-2 `cluster resources:
- eks
- components
- VPC (networking)
Switching to `aws eks` for obtaining kubeconfig in favour of existing divergence pipeline (s3 download  & `kubectl config`), consequently removing some redundant env vars.

Live 2 divergence #4108

---

pipelines/manager/main/infrastructure-account.yaml
pipelines/manager/main/infrastructure-global-resources.yaml
pipelines/manager/main/infrastructure-vpc.yaml

This is for vpc, global and account pipelines, so they get triggered only for related changes
Currently they get trigger on any changes in the infrastructure repo

Update infrastructure pipeline pull-request path

---

pipelines/manager/main/environments-live-2.yaml

Increasing the minutes as there is delay in between merging a commit in git and running the command.
The checks are done every minute and it takes another 2 minutes to get tools image and to start the apply command. By the time, the command is run, the commit time is past 1 minute so the PRs are missed to apply. This gives a safeguard of applying all PRs that are merged past 5 minutes. 
The pipelines are run in serial, so wont be any overlapping of applying a namespace by 2 runs simultaneously. And for terraform resources, there is also state lock.

Increase minutes to look for PRs

---

pipelines/manager/main/create-cluster.yaml

a new `cloud-platform` subcommand exists called `cluster create`. This allows the caller to build a cloud-platform eks cluster with all the components necessary for it to be functional. This commit adds a new pipeline that will eventually supercede the current Ruby script.

Add new create-cluster pipeline

---

pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

Reverts ministryofjustice/cloud-platform-terraform-concourse#171
Now the k8s 1.22 upgrade is complete. All code changes are merged to main, enable the infrastructure pipelines for manager,live-2 and live

Revert "Remove infrastructure pipelines until the 1.22 upgrade is complete"

---

pipelines/manager/main/infrastructure-vpc-live-1.yaml
pipelines/manager/main/infrastructure-vpc-live-2.yaml

This PR renames infrastructure-vpc pipeline to infrastructure-vpc-live-1 and add a new pipeline for terraform plan/apply for vpc live-2

Rename live - live-1 and add live-2 vpc pipeline

---

main.tf
variables.tf
versions.tf

This PR:
- removes the unused `rds_name` local variable
- switches the legacy `//` comment to a `#` comment
- removes the unused `cluster_name` and `is_prod` variables
- pins minimum Terraform and Terraform provider versions
(this PR is a no-op)

Refactor to meet standardised Terraform structure and remove legacy syntax

---

policy.tf
versions.tf

This PR should fix the failing Concourse job to apply [this PR](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-baselines/commit/665a9e98ca7bc4c57ff6db4b188029a00e67e566).

Add IAM Access Analyzer permissions to global_account_policy

---

pipelines/manager/main/environments-live-2.yaml

triggering condition(len(path) > 0) in the pr-github-resource performs an inefficient search of all PRs closed and open in a repository. This quickly eats up our finite GitHub API calls.

Remove path and format yaml

---

pipelines/manager/main/environments-live.yaml

This PR updates the apply and plan-live pipelines to use cloud-platform cli to perform plan/apply namespaces

Use cloud-platform cli for apply, plan jobs

---

pipelines/manager/main/environments-live.yaml

Bump cli image to 1.22.12 which has fix to not error when resources folder doesnot exists in any namespace

Bump cli to 1.22.12

---

pipelines/manager/main/environments-live.yaml

This is to test the cli binary with terraform version 1.2.5 on environments to perform manual plan

Use latest cli with terraform 1.2.5 on plan-manually job

---

pipelines/manager/main/environments-live.yaml

This PR will use the latest CLI with terraform version 1.2.5. When the pipeline uses this image, the terraform state of all namespace will be updated with 1.2.5. When testing, there are few resource changes as mentioned in this ticket: https://github.com/ministryofjustice/cloud-platform/issues/4356

Bump cli to 1.24.0 which has terraform 1.2.5

---

pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

This PR upgrades cloud-platform-tools image to v2.3.0 for enabling terraform upgrade in cloud-platform-infrastructure pipelines

upgrade tools image to 2.3.0 for live/2/manager infra pipelines

---

pipelines/manager/main/infrastructure-manager.yaml

This PR restores the insfrastructure manager pipeline plan jobs for eks and components, now using cloud-platform-cli terraform plan command

add infrastructure-manager plan using cp-cli

---

pipelines/manager/main/eks-create-test-destroy.yaml

Hook new cluster delete cmd in the cp cli into the `eks-create-test-destroy` pipeline

fix: 🐛 outputs to keyval eks-create-test-destroy.yaml

---

pipelines/manager/main/environments-live.yaml

The apply-live pipeline is getting `timeout exceeded` error. As the number of namespaces have increased recently 1 full run is taking more than 4 hours to finish.

Increase timout for apply-live job

---

pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

Reverts ministryofjustice/cloud-platform-terraform-concourse#267
The kubernetes 1.23 upgrade is complete, bring back the infra-apply pipelines.

Revert "Remove infra-apply job for live and manager cluster"

---

pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/divergence-live-2.yaml
pipelines/manager/main/divergence.yaml
pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml
pipelines/manager/main/maintenance.yaml

Reverts ministryofjustice/cloud-platform-terraform-concourse#282
The CLI version from 1.26.8 to 1.27.1 has few dependabot changes and it breaks the pipeline when getting the kubeconfig. Reverting this until the issue is investigated and fixed

Revert " Replace destroy-delete-namespace ruby script to cp cli"

---

pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/maintenance.yaml

This PR bumps the cli image to 1.28.0
The latest cli has the `cloud-platform environment delete` command which is used by destroy-deleted-namespaces pipeline.
The pipeline also includes the PIPELINE_CLUSTER_DIR which replaces PIPELINE_CLUSTER in order to differentiate the cluster context with the folder structure of the environments repo

Bump cli image on all pipelines

---

pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/delete-cluster.yaml

This is the first step to creating a better workflow around deleting test clusters. This step removes the need to edit or "hijack" other pipelines, this makes a dedicated pipeline that handles deleting clusters.
The next step will wrap the fly commands below into our cli reducing overheads for devs
note: because we are leaning on the cli command we are protected against accidentally deleting `live*` or `manager`
```
fly --target $TEST_CONCOURSE_NAME login --team-name main --concourse-url https://concourse.apps.$CLUSTER_NAME.cloud-platform.service.justice.gov.uk/
fly -t $TEST_CONCOURSE_NAME set-pipeline -p delete-cluster -c pipelines/manager/main/delete-cluster.yaml -v cluster_name=$CP-BLAH-BLAH
fly -t $TEST_CONCOURSE_NAME unpause-pipeline -p delete-cluster # only need to do this when …
```

feat: 🎸 add dedicated delete test cluster pipeline, remove old

---

pipelines/manager/main/environments-live.yaml

to cover long running opensearch upgrade jobs

increase apply-namespace-changes-live timeout to 2hrs

---

policy.tf

Concourse pipeline fails with 
```reading IAM User Policy (ecr-user-XXXX:ecr-read-write): AccessDenied: User: arn:aws:iam::XXX:user/cloud-platform/manager-concourse is not authorized to perform: iam:GetUserPolicy on resource: user ecr-user-XXXX because no identity-based policy allows the iam:GetUserPolicy action```

Add GetUserPolicy permission to all iam users

---

pipelines/manager/main/environments-live.yaml

- Bump cli for environments-live pipeline
- include remainder to the chunks count

Bump CLI, Include remainder to fix odd splits

---

policy.tf

To fix concourse failure: AccessDenied: User: XXX../cloud-platform/manager-concourse is not authorized to perform: iam:DetachUserPolicy on resource: user alfresco_user_poc

Add DetachUserPolicy needed when renaming iam users

---

pipelines/manager/main/create-cluster.yaml

The re-adds creation of the OIDC connector. It adds about 10 minutes to create cluster but saves manually creating the resource when working with a test cluster.

Remove fast option from cluster create

---

pipelines/manager/main/migrate-module.yaml

This pr enable the migrate-module pipeline to migrate individual resources.
Associated issue: https://github.com/ministryofjustice/cloud-platform/issues/5318
A succesful run can be found - https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/migrate-module/jobs/migrate/builds/15
Sample command - `fly -t moj-cp set-pipeline --pipeline migrate-module --config migrate-module.yaml -v cluster_name=cp-0306-0730 -v module=tigera_calico -v resources=kubectl_manifest.calico_crds,http.calico_crds`
Key updates:
* parameterised mtm version
* add new parameter for comma seperated resources

chore: update migrate module to include resource migration

---

pipelines/manager/main/bootstrap.yaml
pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/custom-cluster.yaml
pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/infrastructure-account.yaml
pipelines/manager/main/infrastructure-global-resources.yaml
pipelines/manager/main/infrastructure-vpc-live-1.yaml
pipelines/manager/main/infrastructure-vpc-live-2.yaml
pipelines/manager/main/maintenance.yaml
pipelines/manager/main/migrate-module.yaml
pipelines/manager/main/reporting.yaml
pipelines/manager/main/vulnerability-report.yaml

https://github.com/ministryofjustice/cloud-platform-tools-image/releases/tag/2.9.5
Closes: https://github.com/ministryofjustice/cloud-platform/issues/5711

Bump tools-image to latest version 2.9.5

---

policy.tf

Fix below error
```
FATA[0063] error running terraform on namespace hmpps-integration-api-dev: unable to apply Terraform: exit status 1
Error: updating tags for CloudWatch Metric Alarm (arn:aws:cloudwatch:eu-west-2:754256621582:alarm:hmpps-integration-api-dev-gateway-4XX-errors): tagging resource (arn:aws:cloudwatch:eu-west-2:754256621582:alarm:hmpps-integration-api-dev-gateway-4XX-errors): AccessDenied: User: arn:aws:iam::754256621582:user/cloud-platform/manager-concourse is not authorized to perform: cloudwatch:TagResource on resource: arn:aws:cloudwatch:eu-west-2:754256621582:alarm:hmpps-integration-api-dev-gateway-4XX-errors because no identity-based policy allows the cloudwatch:TagResource action
status code: 403, request id: 118f55cc-eee4-4360-853d-c0f60eebaf64
with …
```

feat: Update CloudWatch Tagging Permission

---

pipelines/manager/main/custom-cluster.yaml

This PR adds jobs to the custom cluster pipeline for plan and apply tasks for `eks`, `core` and `components` terraform. This allows a CP team member to manually trigger each of these builds against their test cluster and infrastructure branch.
`fly -t manager set-pipeline -p custom-cluster -c pipelines/manager/main/custom-cluster.yaml -v branch_name=[YOUR BRANCH] -v cluster_name=[YOUR CLUSTER NAME]`

feat: 🎸 add custom cluster plan/apply jobs

---

policy.tf

This will give the concourse IAM policy permission to create AWS Backup resources - used for the s3 module backup option
[Example of fail due to not having permission](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/6513#L66bcba0d:34)

Add permissions for AWS Backups

---

policy.tf

This PR adds `backup-storage:*` permissions to the concourse IAM role.
This will allow concourse to create AWS Backup resources.
[Failed apply due to not having these permissions](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/6691#L66bd1fd7:26) - this policy already contains `kms:*`

Add backup-storage permissions to enable AWS Backups service

---

pipelines/manager/main/cordon-and-drain-nodes.yaml

- missing var which was previously passed in when calling the script

fix: 🐛 hotfix missing var

---

pipelines/manager/main/cordon-and-drain-nodes.yaml

I've tested the cleanup script again and it does work but we just were suffering from the concourse issue of output taking a long time
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/cordon-and-drain-nodes/jobs/cordon-and-drain-nodes/builds/94
nodes are also correctly being deleted from the asg now too

Add cleanup

---

pipelines/manager/main/cordon-and-drain-nodes.yaml

Terraform fails to delete the node group with the following error
```
Error: waiting for EKS Node Group (live:live-def-ng-20240814092yyyyyyyy00f) delete: unexpected state 'DELETE_FAILED', wanted target ''. last error: eks-live-def-ng-202408xxxxxxxxxxxxxf-eac8a81b-d82d-80d0-73b8-cdffc29c54da: AutoScalingGroupInvalidConfiguration: Couldn't terminate instances in ASG as Terminate process is suspended
```

fix: 🐛 allow node group to be deleted

---

pipelines/manager/main/environments-live.yaml

- pass the build url to the apply live pipelines so that if it fails on an rds version mismatch the failed pipeline URL can be included in the correcting PR

chore: 🤖 pass build url to apply live pipelines

---

pipelines/manager/main/environments-live.yaml

You don't actually have access to the BUILD vars inside the task so we can't pass the build URL this way
This reverts commit 678b352a3b213640b000f9d3c7a7859bef791f50.

Revert "chore: 🤖 pass build url to apply live pipelines (#419)"

---

pipelines/manager/main/environments-live.yaml

Sadly we don't have access to the build vars inside the concourse task, so provide a more generic build url

chore: 🤖 add more fixed url

---

pipelines/manager/main/cordon-and-drain-nodes.yaml
pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/custom-cluster.yaml
pipelines/manager/main/delete-cluster.yaml
pipelines/manager/main/divergence-live-2.yaml
pipelines/manager/main/divergence.yaml
pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml
pipelines/manager/main/maintenance.yaml

2/2
This PR pushes the plan file from the pipeline to our s3 bucket and respectively pulls the correct file from s3 to be used in terraform apply
- after plan cmd has ran, and plan files are created push the plan to s3
- before apply cmd has ran, pull the plan file from s3 and use that in the apply cmd

Plan push and pull to and from s3 

---

pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml

We don't have access to the pr id everywhere so use the commit id, it makes more sense like this too.

fix: 🐛 use commit hash instead of pr for id in plan file

---

pipelines/manager/main/maintenance.yaml

remove unused resource
```
error: invalid pipeline config:
invalid resources:
resource 'cloud-platform-environments-repo' is not used
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/bootstrap/jobs/bootstrap-pipelines/builds/3944

fix: Remove unused resource repo

---

pipelines/manager/main/environments-live.yaml

- The current variable `BUILD_URL` is as below:, there is an expected extra `created,` in the output, which caused the [notifyUserApplyFailed](https://github.com/ministryofjustice/cloud-platform-cli/blob/47b420a264ad550f579d74a3c840d15996d7ba93/pkg/environment/apply.go#L50) cannot work properly and cannot send message to Slack.
```
→ curl -L \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer $GITHUB_TOKEN" \
-H "X-GitHub-Api-Version: 2022-11-28" \
"https://api.github.com/repos/ministryofjustice/cloud-platform-environments/issues/$PR/comments" | jq '.[].body' | awk '{print $9}' | tr -d '"'
```
Output:
```
created,
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/9493
```
- This PR is …

fix: Update Curl Command for Build_URL

---

pipelines/manager/main/cordon-and-drain-nodes.yaml
pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/custom-cluster.yaml
pipelines/manager/main/delete-cluster.yaml
pipelines/manager/main/divergence-live-2.yaml
pipelines/manager/main/divergence.yaml
pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml
pipelines/manager/main/maintenance.yaml

- bump cli version 
- https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.39.2

chore: bump cli version

---

example/concourse.tf
example/variables.tf
pipelines/manager/main/environments-live.yaml

- for each of the 5 apply-live jobs, capture failed namespaces and their associated error messages, format as csv and push to s3
- scheduled daily am task to pull csvs, collate and reformat in json, push back to s3
A bit of cleanup to do here still (ie make use of s3 bucket name var import) but keen to get running this afternoon and into the morning for an initial run.
relates to ministryofjustice/cloud-platform#6461

Catch errored ns

---

pipelines/manager/main/hoodaw.yaml

a little bit of a hack to reformat the ruby dashboard report, we can integrate this into the base hoodaw repo when we've finished refactoring to go?
closes  ministryofjustice/cloud-platform#6461

feat: 🎸 update hoodaw slack to include erroring namespaces

---

pipelines/manager/main/cordon-and-drain-nodes.yaml
pipelines/manager/main/create-cluster.yaml
pipelines/manager/main/custom-cluster.yaml
pipelines/manager/main/delete-cluster.yaml
pipelines/manager/main/divergence-live-2.yaml
pipelines/manager/main/divergence.yaml
pipelines/manager/main/eks-create-test-destroy.yaml
pipelines/manager/main/environments-live.yaml
pipelines/manager/main/hoodaw.yaml
pipelines/manager/main/infrastructure-live-2.yaml
pipelines/manager/main/infrastructure-live.yaml
pipelines/manager/main/infrastructure-manager.yaml
pipelines/manager/main/maintenance.yaml
pipelines/manager/main/s3-bucket-deleter.yaml

- export RDS related error to csv after running `apply-live-x` pipeline and upload to S3
- Create new pipeline to run `cloud-platform-cli` against the S3 csv file in `cloud-platform-environment` directory for rds drift
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6956

feat: Create new pipeline for RDS drift

---

pipelines/manager/main/environments-live.yaml

- add `process-rds-error-namespaces` to group

fix: add group for process-rds-error-namespaces

---

pipelines/manager/main/environments-live.yaml

- Run `auto-approve.sh` from the `opa-auto-approve-policy` folder so we don't rely on the cli image to update the script

feat: run auto approve from folder

---

pipelines/manager/main/environments-live.yaml

- I've moved the opa-auto-approve code to it's own repo, this makes our plan-live pipeline use it.
- I don't like line 940 but it's the only way I can do this without breaking ongoing jobs while testing

feat: run opa from it's own repo

---

pipelines/manager/main/environments-live.yaml

- Capture each Concourse build number in the error CSV generated by apply-live-a, so we can trace every namespace error back to the exact Concourse build.
- Adds a tiny “metadata printer” resource (build-env-printer) and a build-env resource instance.
- Inserts a put / get pair that writes Concourse build metadata (BUILD_NAME, etc.) to the files.
- Exposes those files to the apply-environments task and exports them as env vars.
- Updates the awk that writes build-errors-a.csv to include the exported build_name.
- Leaves all other logic, outputs, and S3 uploads unchanged in the apply-live-a 
Output from a task in my test pipeline:
```
use-build-metadata
selected worker: ac28a4b81409
=== Build metadata from resource files ===
atc_external_url: http://localhost:8080
build_id: 2 …
```

fix: pass pipeline env var artifact to the task

---

pipelines/manager/main/environments-live.yaml

Ensures build_name="$BUILD_NAME" is what's rightly used to generate build-names in the s3 bucket and also generates all the pipeline metadata in the loop.
- replaces build_name="$build_name" with build_name="$BUILD_NAME" 
- replaces /BUILD_NAME with /* in the loop as test showed /BUILD_NAME doesn't exist.

Fix build name

---

pipelines/manager/main/environments-live.yaml

Capture each Concourse build number in the error CSV generated by apply-live-c, so we can trace every namespace error back to the exact Concourse build.
- Adds a tiny “metadata printer” resource (build-env-printer) and a build-env resource instance.
- Inserts a put / get pair that writes Concourse build metadata (BUILD_NAME, etc.) to the files.
- Exposes those files to the apply-environments task and exports them as env vars.
- Updates the awk that writes build-errors-c.csv to include the exported build_name.
- Leaves all other logic, outputs, and S3 uploads unchanged in the apply-live-c
Related to https://github.com/ministryofjustice/cloud-platform/issues/6832

feat: add build-name to apply-live-c

---

pipelines/manager/main/environments-live.yaml

Purpose
Capture each Concourse build number in the error CSV generated by apply-live-e, so we can trace every namespace error back to the exact Concourse build.
What this does?
Adds a tiny “metadata printer” resource (build-env-printer) and a build-env resource instance.
Inserts a put / get pair that writes Concourse build metadata (BUILD_NAME, etc.) to the files.
Exposes those files to the apply-environments task and exports them as env vars.
Updates the awk that writes build-errors-e.csv to include the exported build_name.
Leaves all other logic, outputs, and S3 uploads unchanged in the apply-live-e
Related to https://github.com/ministryofjustice/cloud-platform/issues/6832

add build-name to apply-live-e

---

pipelines/manager/main/environments-live.yaml

This adds a fallback to the script i.e. **build-name** to fix this issue in the pipeline which prevents the build name from being exported to the s3 bucket:
`cat: ../build-name/BUILD_NAME: No such file or directory`
- Replaces **BUILD_NAME=$(cat ../build-name/BUILD_NAME | tr -d '\n')** with **BUILD_NAME=$(cat ../build-name/BUILD_NAME 2>/dev/null || cat ../build-name/build_name 2>/dev/null | tr -d '\n')**

fix: add build name fallback to fix error

---

pipelines/manager/main/environments-live.yaml

Collates all newly-added scripts in with build-ids in job tasks `a to e` into **gathered-namespaces-errors.json file.**
All comments will be removed once all necessary changes are fully set up (as highlighted in the ticket).

feat: collate all newly-added files with build ids into one .json file

---

pipelines/manager/main/opensearch.yaml

- update the `SLACK_WEBHOOK_URL` to point to #lower-priority-alarms (it was pointing to ask channel)
- remove unused `SLACK_BOT_TOKEN`

fix: update slack webhook and remove unused variable

---

README.md
hoodaw_irsa.tf

[release](https://github.com/ministryofjustice/cloud-platform-terraform-irsa/releases/tag/2.1.0)

chore: 🤖 bump irsa module version to latest
